
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
#  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#  token-validity-in-seconds: 86400
#echo 'cen-cenlots-dw-spring-boot-jwt-secret-2024-12'|base64
  secret: 9F49BE664A28861CD323A019EF83B9CC4A8F6C987D553C83008D65B0E206D33A6F162B68DF88999BEA7A65156FEC294C9263F8334DDD29303258C945FFEEAAE4
  refresh-token-validity-in-seconds: 604800 #1일은 86,400  7일 × 86,400 = 604,800
  access-token-validity-in-seconds: 14400 # 1시간-> 3600 4시간*3600 = 14400

file:
  directory: ${app.home:${user.home}}/msa-attach-volume # url 사용시에는 사용되지 않는다
  url: http://${file.hostname:localhost} # nginx 로 파일 다운로드 처리

messages:
  directory: test # ${user.dir}/msa-attach-volume/messages

api:
  servicecall:
    #base:
     # url: http://cenlots2024-cenlots-api-service
      #port: 8080
    lotuserservice:
      url: http://cenlots2024-lotuserservice-service
    gamemngservice:
      url: http://cenlots2024-gamemngservice-service
    gamepowerballservice:
      url: http://cenlots2024-gamepowerballservice-service
    cashbackservice:
      url: http://cenlots2024-gamecblottoservice-service
    callurllist: 
      url: /api/v1/rest/selectCallUriRltn
    prevLotto645: /game-lotto645-service
    prevLotto649: /game-lotto649-service

spring:
  web:
    locale: en
